logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기

spring:
  datasource:
    url: { DB_URL }
    username: { DB_USERNAME }
    password: { DB_PASSWORD }
    driver-class-name: { DB_DRIVER_CLASS_NAME }

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: validate
