logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

cors:
  allowedOrigins: http://localhost:3000

oauth:
  kakao:
    client_id:
    redirect_uri:
    client_secret:
    scope:
    admin_key:
  naver:
    client_id:
    redirect_uri:
    client_secret:
    scope:
    state:
  google:
    client_id:
    redirect_uri:
    client_secret:
    scope:

server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: false
        secure: false
aws:
  s3:
    bucket:
    key:
